///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class ImagePath {
  ImagePath._();

  static const String fontsOpenSansBold = 'assets/fonts/OpenSans-Bold.ttf';
  static const String fontsOpenSansMedium = 'assets/fonts/OpenSans-Medium.ttf';
  static const String fontsOpenSansRegular = 'assets/fonts/OpenSans-Regular.ttf';
  static const String fontsOpenSansSemiBold = 'assets/fonts/OpenSans-SemiBold.ttf';
  static const String fontsPoppinsBold = 'assets/fonts/Poppins-Bold.ttf';
  static const String fontsPoppinsExtraBold = 'assets/fonts/Poppins-ExtraBold.ttf';
  static const String fontsPoppinsMedium = 'assets/fonts/Poppins-Medium.ttf';
  static const String fontsPoppinsRegular = 'assets/fonts/Poppins-Regular.ttf';
  static const String fontsPoppinsSemiBold = 'assets/fonts/Poppins-SemiBold.ttf';
  static const String imagesIcBack = 'assets/images/ic_back.png';
  static const String imagesIcBusiness = 'assets/images/ic_business.svg';
  static const String imagesIcFilter = 'assets/images/ic_filter.png';
  static const String imagesMyBook = 'assets/images/my_book.png';
}
